export const productsList = [
  {
    id: 1,
    title: "Fjallraven Backpack",
    price: 109.95,
    description: "Durable backpack for daily use and laptops.",
    category: "men's clothing",
    image: "https://picsum.photos/seed/bag1/400/400",
    rating: { rate: 3.9, count: 120 },
  },
  {
    id: 2,
    title: "Mens Casual Slim T-Shirt",
    price: 22.3,
    description: "Comfortable cotton slim-fit t-shirt.",
    category: "men's clothing",
    image: "https://picsum.photos/seed/shirt1/400/400",
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 3,
    title: "Mens Cotton Jacket",
    price: 55.99,
    description: "Perfect jacket for winter and travel.",
    category: "men's clothing",
    image: "https://picsum.photos/seed/jacket1/400/400",
    rating: { rate: 4.7, count: 500 },
  },
  {
    id: 4,
    title: "Mens Casual Slim Fit Shirt",
    price: 15.99,
    description: "Lightweight casual shirt for daily wear.",
    category: "men's clothing",
    image: "https://picsum.photos/seed/shirt2/400/400",
    rating: { rate: 2.1, count: 430 },
  },
  {
    id: 5,
    title: "Gold & Silver Bracelet",
    price: 695,
    description: "Premium handcrafted bracelet.",
    category: "jewelery",
    image: "https://picsum.photos/seed/jewel1/400/400",
    rating: { rate: 4.6, count: 400 },
  },
  {
    id: 6,
    title: "Solid Gold Micropave Ring",
    price: 168,
    description: "Elegant gold ring with micropave design.",
    category: "jewelery",
    image: "https://picsum.photos/seed/jewel2/400/400",
    rating: { rate: 3.9, count: 70 },
  },
  {
    id: 7,
    title: "White Gold Princess Ring",
    price: 9.99,
    description: "Beautiful white gold plated ring.",
    category: "jewelery",
    image: "https://picsum.photos/seed/jewel3/400/400",
    rating: { rate: 3.0, count: 400 },
  },
  {
    id: 8,
    title: "Rose Gold Earrings",
    price: 10.99,
    description: "Stylish rose gold plated earrings.",
    category: "jewelery",
    image: "https://picsum.photos/seed/jewel4/400/400",
    rating: { rate: 1.9, count: 100 },
  },
  {
    id: 9,
    title: "Portable External Hard Drive 2TB",
    price: 64,
    description: "Fast and reliable external hard drive.",
    category: "electronics",
    image: "https://picsum.photos/seed/elect1/400/400",
    rating: { rate: 3.3, count: 203 },
  },
  {
    id: 10,
    title: "SSD 1TB Internal Drive",
    price: 109,
    description: "High speed SSD for better performance.",
    category: "electronics",
    image: "https://picsum.photos/seed/elect2/400/400",
    rating: { rate: 2.9, count: 470 },
  },
  {
    id: 11,
    title: "256GB SATA SSD",
    price: 109,
    description: "Reliable SSD with fast read/write speed.",
    category: "electronics",
    image: "https://picsum.photos/seed/elect3/400/400",
    rating: { rate: 4.8, count: 319 },
  },
  {
    id: 12,
    title: "4TB Gaming External Drive",
    price: 114,
    description: "Best storage option for gamers.",
    category: "electronics",
    image: "https://picsum.photos/seed/elect4/400/400",
    rating: { rate: 4.8, count: 400 },
  },
  {
    id: 13,
    title: "21.5 Inch Full HD Monitor",
    price: 599,
    description: "Ultra-thin IPS monitor with vivid display.",
    category: "electronics",
    image: "https://picsum.photos/seed/monitor1/400/400",
    rating: { rate: 2.9, count: 250 },
  },
  {
    id: 14,
    title: "49 Inch Curved Gaming Monitor",
    price: 999.99,
    description: "Super ultrawide curved gaming monitor.",
    category: "electronics",
    image: "https://picsum.photos/seed/monitor2/400/400",
    rating: { rate: 2.2, count: 140 },
  },
  {
    id: 15,
    title: "Women's Winter Jacket",
    price: 56.99,
    description: "3-in-1 winter jacket for snow and rain.",
    category: "women's clothing",
    image: "https://picsum.photos/seed/women1/400/400",
    rating: { rate: 2.6, count: 235 },
  },
  {
    id: 16,
    title: "Women's Faux Leather Jacket",
    price: 29.95,
    description: "Stylish faux leather biker jacket.",
    category: "women's clothing",
    image: "https://picsum.photos/seed/women2/400/400",
    rating: { rate: 2.9, count: 340 },
  },
  {
    id: 17,
    title: "Women's Rain Jacket",
    price: 39.99,
    description: "Lightweight raincoat with hood.",
    category: "women's clothing",
    image: "https://picsum.photos/seed/women3/400/400",
    rating: { rate: 3.8, count: 679 },
  },
  {
    id: 18,
    title: "Women's Boat Neck T-Shirt",
    price: 9.85,
    description: "Soft and stretchy casual t-shirt.",
    category: "women's clothing",
    image: "https://picsum.photos/seed/women4/400/400",
    rating: { rate: 4.7, count: 130 },
  },
  {
    id: 19,
    title: "Women's Moisture Wicking T-Shirt",
    price: 7.95,
    description: "Breathable fabric for workouts.",
    category: "women's clothing",
    image: "https://picsum.photos/seed/women5/400/400",
    rating: { rate: 4.5, count: 146 },
  },
  {
    id: 20,
    title: "Women's Casual Cotton T-Shirt",
    price: 12.99,
    description: "Comfortable cotton casual wear.",
    category: "women's clothing",
    image: "https://picsum.photos/seed/women6/400/400",
    rating: { rate: 3.6, count: 145 },
  },
];
